headers = []
redirects = []

[build]
publish = "dist/client"
command = "vite build"

  [build.environment]

  [build.processing]

    [build.processing.css]

    [build.processing.html]

    [build.processing.images]

    [build.processing.js]

  [build.services]

[database]

  [database.migrations]
  path = "netlify/database/migrations"

[dev]
command = "npm run dev"
targetPort = 3000
port = 8888

[functions]

  [functions."*"]

[[plugins]]
origin = "ui"
package = "@netlify/plugin-lighthouse"

  [plugins.inputs]