/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TaxCalculatorRouteImport } from './routes/tax-calculator'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketplaceIndexRouteImport } from './routes/marketplace/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as MarketplaceVehicleIdRouteImport } from './routes/marketplace/$vehicleId'

const TaxCalculatorRoute = TaxCalculatorRouteImport.update({
  id: '/tax-calculator',
  path: '/tax-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIndexRoute = MarketplaceIndexRouteImport.update({
  id: '/marketplace/',
  path: '/marketplace/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceVehicleIdRoute = MarketplaceVehicleIdRouteImport.update({
  id: '/marketplace/$vehicleId',
  path: '/marketplace/$vehicleId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/tax-calculator': typeof TaxCalculatorRoute
  '/marketplace/$vehicleId': typeof MarketplaceVehicleIdRoute
  '/admin/': typeof AdminIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/tax-calculator': typeof TaxCalculatorRoute
  '/marketplace/$vehicleId': typeof MarketplaceVehicleIdRoute
  '/admin': typeof AdminIndexRoute
  '/marketplace': typeof MarketplaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/tax-calculator': typeof TaxCalculatorRoute
  '/marketplace/$vehicleId': typeof MarketplaceVehicleIdRoute
  '/admin/': typeof AdminIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/tax-calculator'
    | '/marketplace/$vehicleId'
    | '/admin/'
    | '/marketplace/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/tax-calculator'
    | '/marketplace/$vehicleId'
    | '/admin'
    | '/marketplace'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/tax-calculator'
    | '/marketplace/$vehicleId'
    | '/admin/'
    | '/marketplace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  TaxCalculatorRoute: typeof TaxCalculatorRoute
  MarketplaceVehicleIdRoute: typeof MarketplaceVehicleIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tax-calculator': {
      id: '/tax-calculator'
      path: '/tax-calculator'
      fullPath: '/tax-calculator'
      preLoaderRoute: typeof TaxCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/marketplace'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof MarketplaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/$vehicleId': {
      id: '/marketplace/$vehicleId'
      path: '/marketplace/$vehicleId'
      fullPath: '/marketplace/$vehicleId'
      preLoaderRoute: typeof MarketplaceVehicleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  TaxCalculatorRoute: TaxCalculatorRoute,
  MarketplaceVehicleIdRoute: MarketplaceVehicleIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
